# Book settings
title: Taxcalc-Payroll
author: Bodi Yang
logo: ospc-aei.png
exclude_patterns: [guide/make, guide/templates, recipes/md_src, '**/README.md']
repository:
  url: https://github.com/bodiyang/Taxcalc-Payroll
  path_to_book: docs
  branch: master
html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"
  notebook_interface: "classic" # or "jupyterlab"
execute:
  timeout: -1
  execute_notebooks: 'off'

  #######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          : ['sphinx.ext.autodoc', 'sphinx.ext.mathjax',
                               'sphinx.ext.viewcode', 'sphinx.ext.napoleon',
                               'alabaster']   # A list of extra extensions to load by Sphinx.
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
